spring:
  application:
    name: payflow

  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_db
    username: payflow
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8080